version: "3.3"

services:
  db:
    image: postgres:14.6
    shm_size: 1g
    volumes:
      - ./containers_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  backend:
    build: .
    user: "${UID}:1000"
    command: /bin/bash create_initial_migration.sh
    volumes:
      - ./partmanager:/code
      - ${PARTS_DB_DIR}:/var/partsdb
      - ${STATIC_DIR}:/var/static
      - ${MEDIA_DIR}:/var/media
      - ${LOG_DIR}:/var/log/shelftracker
      - ${CONFIG_DIR}:/etc/shelftracker
      - ./containers_data/tmp:/tmp
    ports:
      - "${PART_MANAGER_PORT}:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - ${REDIS_PORT}

  celery:
    build: .
    user: "${UID}:1000"
    command: ["celery", "-A", "partmanager", "worker", "--loglevel=info"]
    volumes:
      - ./partmanager:/code
      - ${PARTS_DB_DIR}:/var/partsdb
      - ${STATIC_DIR}:/var/static
      - ${MEDIA_DIR}:/var/media
      - ${LOG_DIR}:/var/log/shelftracker
      - ${CONFIG_DIR}:/etc/shelftracker
      - ./containers_data/tmp:/tmp
    depends_on:
      - redis